# Generated by Django 2.2.5 on 2020-06-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Cloth Category',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ClothColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Cloth Color',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ClothSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Cloth Size',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('fabric', models.CharField(max_length=40)),
                ('is_new', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('category', models.ManyToManyField(blank=True, related_name='clothes', to='clothes.ClothCategory')),
                ('color', models.ManyToManyField(blank=True, related_name='clothes', to='clothes.ClothColor')),
                ('size', models.ManyToManyField(blank=True, related_name='clothes', to='clothes.ClothSize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
