# Generated by Django 2.2.5 on 2020-06-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20200616_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='cloth_photos')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clothes.Cloth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
